language: node_js
node_js:
  - '0.12'
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
before_install:
  - curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | bash -
services: mongodb
